"""empty message

Revision ID: fcbb129ab25b
Revises: 257a34948fd9
Create Date: 2022-09-11 00:58:22.981231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbb129ab25b'
down_revision = '257a34948fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'age')
    # ### end Alembic commands ###
